# Spam Detector

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

## Retrieve the Data

The data is located at [https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv](https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv)

Dataset Source: [UCI Machine Learning Library](https://archive.ics.uci.edu/dataset/94/spambase)

Import the data using Pandas. Display the resulting DataFrame to confirm the import was successful.

In [ ]:
# Import the data
data = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m13/challenge/spam-data.csv")
data.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.00  ...         0.00        0.000   
1             0.00            0.94  ...         0.00        0.132   
2             0.64            0.25  ...         0.01        0.143   
3             0.31            0.63  ...         0.00        0.137   
4             0.31            0.63  ...         0.00        0.135   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.778        0.000        0.000   
1          0.0        0.372        0.180        0.048   
2          0.0        0.276        0.184        0.010   
3          0.0        0.137        0.000        0.000   
4          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  spam  
0                       278     1  
1                      1028     1  
2                      2259     1  
3                       191     1  
4                       191     1  

[5 rows x 58 columns]

## Predict Model Performance

You will be creating and comparing two models on this data: a Logistic Regression, and a Random Forests Classifier. Before you create, fit, and score the models, make a prediction as to which model you think will perform better. You do not need to be correct!

Write down your prediction in the designated cells in your Jupyter Notebook, and provide justification for your educated guess.

*Replace the text in this markdown cell with your predictions, and be sure to provide justification for your guess.*

## Split the Data into Training and Testing Sets

In [ ]:
data['spam'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4601 entries, 0 to 4600
Series name: spam
Non-Null Count  Dtype
--------------  -----
4601 non-null   int64
dtypes: int64(1)
memory usage: 36.1 KB


In [ ]:
# Create the labels set `y` and features DataFrame `X`
X = data.copy()
X.drop("spam", axis=1, inplace=True)
X.head()


word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.00               0.64           0.64           0.0   
1            0.21               0.28           0.50           0.0   
2            0.06               0.00           0.71           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.32            0.00              0.00                0.00   
1           0.14            0.28              0.21                0.07   
2           1.23            0.19              0.19                0.12   
3           0.63            0.00              0.31                0.63   
4           0.63            0.00              0.31                0.63   

   word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
0             0.00            0.00  ...                   0.0         0.00   
1             0.00            0.94  ...                   0.0         0.00   
2             0.64            0.25  ...                   0.0         0.01   
3             0.31            0.63  ...                   0.0         0.00   
4             0.31            0.63  ...                   0.0         0.00   

   char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0        0.000          0.0        0.778        0.000        0.000   
1        0.132          0.0        0.372        0.180        0.048   
2        0.143          0.0        0.276        0.184        0.010   
3        0.137          0.0        0.137        0.000        0.000   
4        0.135          0.0        0.135        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       3.756                          61   
1                       5.114                         101   
2                       9.821                         485   
3                       3.537                          40   
4                       3.537                          40   

   capital_run_length_total  
0                       278  
1                      1028  
2                      2259  
3                       191  
4                       191  

[5 rows x 57 columns]

In [ ]:
# Define target vector
y = data["spam"].values.reshape(-1, 1)
y[:5]

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
# Check the balance of the labels variable (`y`) by using the `value_counts` function.
data['spam'].value_counts()

spam
0    2788
1    1813
Name: count, dtype: int64

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
X_train

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
1813             0.0                0.0           0.00           0.0   
3029             0.0                0.0           0.00           0.0   
2489             0.0                0.0           0.00           0.0   
3039             0.0                0.0           0.00           0.0   
4571             0.0                0.0           0.46           0.0   
...              ...                ...            ...           ...   
2163             0.0                0.0           0.00           0.0   
3476             0.0                0.0           0.44           0.0   
2744             0.0                0.0           0.00           0.0   
4136             0.0                0.0           0.00           0.0   
470              0.0                0.0           0.00           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
1813           0.00            0.00              0.00                 0.0   
3029           0.00            0.00              0.00                 0.0   
2489           0.00            0.00              0.00                 0.0   
3039           0.00            0.00              0.00                 0.0   
4571           0.23            0.23              0.00                 0.0   
...             ...             ...               ...                 ...   
2163           0.31            0.00              0.31                 0.0   
3476           0.00            0.00              0.00                 0.0   
2744           1.58            0.79              0.00                 0.0   
4136           0.00            0.00              0.00                 0.0   
470            0.00            0.00              0.00                 0.0   

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
1813             0.00             0.0  ...                  0.00        0.022   
3029             0.00             0.0  ...                  0.00        0.000   
2489             0.00             0.0  ...                  0.00        0.325   
3039             0.00             0.0  ...                  0.00        0.000   
4571             0.00             0.0  ...                  0.00        0.000   
...               ...             ...  ...                   ...          ...   
2163             0.31             0.0  ...                  0.00        0.000   
3476             0.00             0.0  ...                  0.44        0.000   
2744             0.00             0.0  ...                  0.00        0.000   
4136             0.00             0.0  ...                  0.00        0.000   
470              0.00             0.0  ...                  0.00        0.000   

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
1813        0.022        0.019        0.022        0.022        0.022   
3029        0.000        0.000        0.000        0.000        0.000   
2489        0.000        0.000        0.000        0.000        0.000   
3039        0.000        0.000        0.000        0.000        0.000   
4571        0.082        0.000        0.082        0.000        0.000   
...           ...          ...          ...          ...          ...   
2163        0.255        0.102        0.000        0.000        0.255   
3476        0.000        0.061        0.000        0.000        0.000   
2744        0.263        0.000        0.000        0.000        0.000   
4136        1.066        0.000        0.213        0.000        0.000   
470         0.000        0.000        5.844        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
1813                       3.482                           5   
3029                       1.000                           1   
2489                       1.000                           1   
3039                       1.526                           7   
4571                       1.256              

In [ ]:
# Split the data into X_train, X_test, y_train, y_test
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3450 entries, 1813 to 470
Data columns (total 57 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_make              3450 non-null   float64
 1   word_freq_address           3450 non-null   float64
 2   word_freq_all               3450 non-null   float64
 3   word_freq_3d                3450 non-null   float64
 4   word_freq_our               3450 non-null   float64
 5   word_freq_over              3450 non-null   float64
 6   word_freq_remove            3450 non-null   float64
 7   word_freq_internet          3450 non-null   float64
 8   word_freq_order             3450 non-null   float64
 9   word_freq_mail              3450 non-null   float64
 10  word_freq_receive           3450 non-null   float64
 11  word_freq_will              3450 non-null   float64
 12  word_freq_people            3450 non-null   float64
 13  word_freq_report            3450 non

## Scale the Features

Use the `StandardScaler` to scale the features data. Remember that only `X_train` and `X_test` DataFrames should be scaled.

In [ ]:
from sklearn.preprocessing import StandardScaler

# Create the StandardScaler instance
scaler = StandardScaler()

In [ ]:
# Fit the Standard Scaler with the training data
# Scaling the X data by using StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[-0.34017612, -0.16575841, -0.55757067, ..., -0.05270072,
        -0.223586  , 10.11579197],
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.1284321 ,
        -0.24237383, -0.49458154],
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.1284321 ,
        -0.24237383, -0.47300112],
       ...,
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.08037532,
        -0.17661644, -0.31294633],
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.11827153,
        -0.23297992, -0.43343702],
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.10811095,
        -0.223586  , -0.47120275]])

In [ ]:
# Scale the test data
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.34017612, -0.16575841, -0.55757067, ..., -0.03689538,
         0.03474658, -0.34711533],
       [-0.34017612, -0.16575841, -0.55757067, ..., -0.12409936,
        -0.223586  , -0.4118566 ],
       [ 1.76873242, -0.16575841,  0.70856673, ..., -0.08449447,
        -0.14373775, -0.27877733],
       ...,
       [-0.34017612,  0.345508  , -0.55757067, ..., -0.07491363,
        -0.12964688, -0.21583444],
       [-0.34017612, -0.16575841,  6.24791788, ..., -0.11317598,
        -0.22828296, -0.47120275],
       [-0.34017612, -0.16575841,  0.273332  , ..., -0.06280027,
        -0.07328341,  0.06291266]])

## Create and Fit a Logistic Regression Model

Create a Logistic Regression model, fit it to the training data, make predictions with the testing data, and print the model's accuracy score. You may choose any starting settings you like.

In [ ]:
# Train a Logistic Regression model and print the model score
from sklearn.linear_model import LogisticRegression
logistic_regression_model = LogisticRegression()


In [ ]:
# Fit the model
logistic_regression_model.fit(X_train, y_train)


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
print(f"Training Data Score: {logistic_regression_model.score(X_train, y_train)}")
print(f"Testing Data Score: {logistic_regression_model.score(X_test, y_test)}")

Training Data Score: 0.923768115942029
Testing Data Score: 0.9183318853171155


In [ ]:
predictions = logistic_regression_model.predict(X_test)

predictions

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
# Make and save testing predictions with the saved logistic regression model using the test data
predictions = logistic_regression_model.predict(X_train)

# Convert those predictions (and actual values) to a DataFrame
results_df = pd.DataFrame({"Prediction": predictions, "Actual": y_train})
results_df
# Review the predictions


array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
y_test = y_test.ravel()

In [ ]:
results_df = pd.DataFrame({
    "Testing Data Predictions": predictions,
    "Testing Data Actual Targets": y_test})
results_df


Testing Data Predictions  Testing Data Actual Targets
0                            1                            1
1                            0                            0
2                            1                            1
3                            1                            0
4                            0                            0
...                        ...                          ...
1146                         0                            0
1147                         1                            1
1148                         0                            0
1149                         0                            0
1150                         0                            0

[1151 rows x 2 columns]

In [ ]:
# Calculate the accuracy score by evaluating `y_test` vs. `testing_predictions`.
from sklearn.metrics import accuracy_score

# Calculate the model's accuracy on the test dataset
accuracy_score(y_test, predictions)


0.9183318853171155

## Create and Fit a Random Forest Classifier Model

Create a Random Forest Classifier model, fit it to the training data, make predictions with the testing data, and print the model's accuracy score. You may choose any starting settings you like.

In [ ]:
# Train a Random Forest Classifier model and print the model score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Train the Random Forest model
clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train, y_train)

# Evaluate the model
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test ,y_test)}')

<ipython-input-39-e3894b2a986f>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train, y_train)


Training Score: 0.9994202898550725
Testing Score: 0.9574283231972198


In [ ]:
# Get the feature importance array
feature_importances = clf.feature_importances_

array([0.00347075, 0.00546196, 0.01127617, 0.00137657, 0.02879435,
       0.00708044, 0.07110051, 0.00868292, 0.00520471, 0.00814709,
       0.01109436, 0.01163656, 0.00397334, 0.00211841, 0.00115573,
       0.06779078, 0.01223453, 0.00999284, 0.03014712, 0.0061457 ,
       0.05587489, 0.00263415, 0.02428033, 0.03097268, 0.04872606,
       0.01818781, 0.02188095, 0.00668595, 0.00155339, 0.00309625,
       0.00159318, 0.00090676, 0.00262595, 0.00077574, 0.00377641,
       0.00357994, 0.01452512, 0.00065544, 0.003058  , 0.00101988,
       0.00119027, 0.00544822, 0.00176672, 0.00232091, 0.01009025,
       0.01807791, 0.00024345, 0.00122754, 0.00496329, 0.01251157,
       0.0025719 , 0.12198556, 0.10008473, 0.00335095, 0.06647989,
       0.05368788, 0.04070521])

In [ ]:
# List the top 10 most important features
importances_sorted = sorted(zip(feature_importances, X.columns), reverse=True)
importances_sorted[:10]

[(0.12198555708128765, 'char_freq_!'),
 (0.10008472839196789, 'char_freq_$'),
 (0.071100508402144, 'word_freq_remove'),
 (0.06779078289210487, 'word_freq_free'),
 (0.06647989169891515, 'capital_run_length_average'),
 (0.05587488601144418, 'word_freq_your'),
 (0.05368787696908879, 'capital_run_length_longest'),
 (0.048726064837327374, 'word_freq_hp'),
 (0.04070521489005327, 'capital_run_length_total'),
 (0.030972680815321927, 'word_freq_money')]

In [ ]:
# Make and save testing predictions with the saved logistic regression model using the test data

predictions_clf = clf.predict(X_test)
# Review the predictions
predictions_clf

array([1, 0, 1, ..., 0, 0, 0])

In [ ]:
# Convert those predictions (and actual values) to a DataFrame
results_df_clf = pd.DataFrame({"Prediction": predictions_clf, "Actual": y_test})
results_df_clf

Prediction  Actual
0              1       1
1              0       0
2              1       1
3              0       0
4              0       0
...          ...     ...
1146           0       0
1147           1       1
1148           0       0
1149           0       0
1150           0       0

[1151 rows x 2 columns]

In [ ]:
# Calculate the accuracy score by evaluating `y_test` vs. `testing_predictions`.
from sklearn.metrics import accuracy_score

# Calculate the model's accuracy on the test dataset
accuracy_score(y_test, predictions_clf)


0.9574283231972198

In [ ]:
# Calculate the accuracy score by evaluating `y_test` vs. `testing_predictions`.


0.9548218940052129

## Evaluate the Models

Which model performed better? How does that compare to your prediction? Write down your results and thoughts in the following markdown cell.

The RandomForestClassifier preformed better than the logistic regression model. I think this is the case because it seemed to account for importances_sorted values which shows that some of the data was just noise